title: Mihail Szabolcs
author: Mihail Szabolcs
email: me(at)mihail(dot)co
description: The ramblings of a code gardener.
url: https://mihail.co
image: /media/misc/me.png
github:
  username: icebreaker
  url: https://github.com/icebreaker
  dotfiles:
    url: https://github.com/icebreaker/dotfiles
  blog:
    url: https://github.com/icebreaker/icebreaker.github.com
  issue: https://github.com/icebreaker/icebreaker.github.com/issues
rss:
  url: https://feeds.feedburner.com/mihailco
twitter:
  url: https://twitter.com/c0d3rguy
  status: https://twitter.com/c0d3rguy/status
permalink: pretty
collections:
  pages:
    output: true
    permalink: /:path/
  topics:
    output: true
exclude:
  - bin/
  - CNAME
  - README.md
  - TODO.md
  - Gemfile
  - Gemfile.lock
  - css/style.tpl
  - css/syntax.tpl
  - .ruby-version
  - .template.md
  - .dotmake
